M48
; DRILL file {KiCad 7.0.7} date Thu Oct  3 14:14:58 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-03T14:14:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.9445Y-1.1744
X4.1355Y-1.1744
T2
X3.9327Y-1.0551
X4.1473Y-1.0551
T0
M30
